### ISSUE TITLE
error when compiling pytorch

### ISSUE THREAD

**Issue by Jimmy2027** [aclex/pytorch-ebuild#15]
Hi @aclex, have you tried compiling pytorch with a newer gcc version?
For me it fails with x86_64-pc-linux-gnu-11.2.0:

[sci-libs_pytorch-1.9.0_20211111-203258.log](https://github.com/aclex/pytorch-ebuild/files/7527787/sci-libs_pytorch-1.9.0_20211111-203258.log)
[emerge_info](https://github.com/aclex/pytorch-ebuild/files/7526023/emerge_info.txt)

**Comment by aclex** [comment]
@Jimmy2027 Hi, Hendrik! Yes, I'm aware of it, unfortunately it fails to compile in one of the dependencies. Looks like a platform-specific type collision, but haven't had enough time to dive into it yet, hope to do it next week.

By the way, your build.log seems to be of `sci-biology/fsl` not Pytorch itself, but the report is still just right :)

**Comment by Jimmy2027** [comment]
ah right sorry, I edited that. Should be the right build log now :)
I tried the build with gcc 9.4.0 and stumbled on another error:
[sci-libs_pytorch-1.9.0_20211112-084456.log](https://github.com/aclex/pytorch-ebuild/files/7527825/sci-libs_pytorch-1.9.0_20211112-084456.log)

With what gcc version are you able to build pytorch?

**Comment by aclex** [comment]
No problem) From your build log it seems your `dev-libs/protobuf` is built against some libstdc++ other than used by the compiler you're using.
I've actually been able to build 1.9.0 successfully with GCC-10.2, if I remember correctly, and now that GCC is bumped to 11.2 it fails to compile for me (haven't saved the build log, unfortunately). Seems there're some more SSE/AVX primitives added to standard headers, which tend to conflict with some types in one of the dependencies.

**Comment by aclex** [comment]
@Jimmy2027 Please take a look at the recent 1.10.0 ebuild, I seem to fix all the problems with compiling with GCC 11, now it builds fine for me. I don't tend to backport this to 1.9.x since there may be other bugs intoduced with this (the failure is in mkl-dnn), but maybe I'll add a restriction on gcc version used.

**Comment by Jimmy2027** [comment]
Hi @aclex, I'm also able to build the 1.10.0 ebuild with GCC 11, thanks a lot :)

**Comment by aclex** [comment]
@Jimmy2027 nice to hear! Thank you very much!
