### ISSUE TITLE
Error building sci-libs/onnx-1.7.0::aclex-pytorch

### ISSUE THREAD

**Issue by equaeghe** [aclex/pytorch-ebuild#16]
I get an error building sci-libs/onnx-1.7.0::aclex-pytorch. It is not exactly clear to me what the underlying issue is, but it seems related to a protobuf upgrade in ::gentoo. In attachment, I put the typical log files. I hope you are able to find out what is wrong.

[onnx-1.7.0_build.log](https://github.com/aclex/pytorch-ebuild/files/7710352/onnx-1.7.0_build.log)
[emerge--info.log](https://github.com/aclex/pytorch-ebuild/files/7710354/emerge--info.log)
[emerge-pqv.log](https://github.com/aclex/pytorch-ebuild/files/7710355/emerge-pqv.log)

**Comment by aclex** [comment]
Thanks for the report!

Oh yes, it looks like the problem with recent Protobuf versions > 3.11: onnx/onnx#2678. It seems to be fixed now, but probably we should bump the ONNX version to apply. I'll look closer at this in the evening, but you can try to use older Protobuf versions meanwhile.

**Comment by aclex** [comment]
I've added a limitation to the existing onnx-1.7.0 and also add an updated ebuild for ONNX. Hopefully it's solved now.
