### ISSUE TITLE
Co-maintaining pytorch in Gentoo Science Overlay

### ISSUE THREAD

**Issue by heroxbd** [aclex/pytorch-ebuild#7]
Hi Alexey,

I have read your `ebuild` and it looks great.  Are you interested in maintaining it in the Gentoo Science Overlay to let more users benefit from your work?  If you are interested, please start from sending a pull request to us.  Your ebuild quality is high. I believe it won't take too long to grant you the commit access to the science overlay. 

I regret that I have made a pytorch ebuild by myself just before discovering your ebuild.  Luckily mine is focused on CUDA, so our works are complementary.

Yours,
Benda

**Comment by aclex** [comment]
@heroxbd Thanks, Benda, thank you very much for your post and kind words about the ebuilds here! Of course, I'd be very happy, if these ebuilds were added to Gentoo Science Overlay and my little contribution might be useful for someone else. I'll prepare the pull request of the current status and post it shortly.

I'm also so sorry, that you had to pay your time for the pytorch ebuild, I can imagine how significant efforts it takes. But yes, I hope, if the ebuilds would be merged, we'll manage to have even more tested and stable result.

So yes, I'll work at it the coming days. Thanks again for your message!

**Comment by heroxbd** [comment]
That would be great!  I am very encouraged and looking forward to working with you.

Thank you so much!

**Comment by aclex** [comment]
@heroxbd Thanks, Benda! I've just sent a pull request with the content of this repository to the Gentoo Science Overlay github project here: https://github.com/gentoo/sci/pull/941. Though my past experience of contributing to Gentoo wasn't particularly successful, well, I was just ignored, hopefully, this time it maybe would be considered. Anyway, thank you very much again for your suggestion and letting me know of this possibility!

**Comment by heroxbd** [comment]
@aclex that's great!  I will look into the PR in the mean time.

Sorry to hear that you were ignored in the past.  You voice might have been overtaken by a lot of bug reports.   Could you please refer to some links of your previous ignored contributions?

**Comment by aclex** [comment]
Yes, sure, I mean, my previous tries were on the main Gentoo repository, not the Scientific Overlay, but yes, here're the links on a couple of little contributions I tried to do: https://github.com/gentoo/gentoo/pull/12938 https://github.com/gentoo/gentoo/pull/14330 I tried to attract some attention by e-mailing maintainer of certain system and asking for help on IRC, but with no success, unfortunately. Hopefully, it's just a bad luck on me :)
