### ISSUE TITLE
error building torchvision

### ISSUE THREAD

**Issue by cnd** [aclex/pytorch-ebuild#9]
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/include/g++-v9/x86_64-pc-linux-gnu/bits/c++config.h:273:27: error: #if with no expression
  273 | #if _GLIBCXX_USE_CXX11_ABI
      |                           ^
```

feels bad, are there patches for it in upstream repo?

**Comment by aclex** [comment]
Hmm, don't really know this time, never happened to me. Looks like kind of C++11 ABI inconsistency somewhere.

**Comment by cnd** [comment]
https://github.com/pytorch/vision/issues/1958
